config/routes.rb
CraigslistJr::Application.routes.draw do
  root to: 'posts#index'
  resources :posts
  resources :categories, :only => :index
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, :only => [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to post_path(@post)
  end

  def edit
  end

  def update
    @post.update(post_params)

    flash.notice = "Post '#{@post.title} Updated!"
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to action: 'index'
  end

  private
  def post_params
    params.require(:post).permit(:title, :owner, :price, :description, :email, :category_id)
  end

  def get_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<div class="row">
<div class="large-12 columns">
    <h1>Categories</h1>
</div>
</div>

<div class="row">
<div class="small-6 large-4 columns">
    <ul id="posts">
        <% @categories.each do |category| %>
            <li>
                <%= link_to category.name, category_path(category) %>
            </li>
        <% end %>
    </ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<section role="main">
  <div class="row">
    <% if flash.notice %>
      <div class="alert-box success large-12 columns">
        <%= flash.notice %>
      </div>
    <% end %>
  </div>
      <%= yield %>
    <%= javascript_include_tag "application" %>
</section>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <ul>
    <% @post.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :description%>
  <%= f.text_area :description %><br>
  <%= f.label :owner%>
  <%= f.text_field :owner %><br>
  <%= f.label :email%>
  <%= f.text_field :email %><br>
  <%= f.label :price%>
  <%= f.number_field :price %><br>
  <%= f.label :category_id%>
  <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] }, { include_blank: '-'} %>
  <%= f.submit class: 'button' %>

<% end %>

app/views/posts/edit.html.erb
<div class="row">
    <div class="large-12 columns">
        <h1>Edit Post</h1>
    </div>
</div>
<div class="row">
      <div>
          <div class="large-9 small-12 columns">
              <%= render partial: 'form' %>
          </div>
      </div>
</div>

app/views/posts/index.html.erb
<div class="row">
<div class="large-12 columns">
    <h1>Posts</h1>
</div>
</div>

<div class="row">
<div class="small-6 large-4 columns">
    <ul id="posts">
        <% @posts.each do |post| %>
            <li>
                <%= link_to post.title, post_path(post) %>
            </li>
        <% end %>
    </ul>
</div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Create New Post</h1>
  </div>
</div>

<div class="row">
  <div class="large-9 small-3 columns"><%= render partial: 'form' %></div>
</div>

app/views/posts/show.html.erb
<div class="row">
<div class="large-12 columns">
<h1><%=@post.title %></h1>
</div>
</div>


<div class="row">
    <div class="large-6 small-12 columns">
        <p>Description: <%= @post.description %></p>
        <div>Contact: <%= @post.owner %> at <%= @post.email %></div>
        <div>Price: <%= number_to_currency @post.price %></div>
    </div>

    <div class="large-6 small-12 columns">
<!--         <h6><#%= link_to "Return to Category #{@post.category.name}", category_path(@post.category) %></h6> -->
        <div><%= link_to "All Posts", posts_path, class: 'small button' %></div>
        <div><%= link_to "Edit", edit_post_path(@post), class: 'small button success' %></div>
        <div><%= link_to "Delete", post_path(@post), class: 'small button alert', method: :delete %></div>
    </div>
</div>